#pragma once

#define WINNETMETER_VERSION 0,1,4,0
#define WINNETMETER_VERSION_STRING "0.1.4"

#define WINNETMETER_WIDEN_INNER(value) L##value
#define WINNETMETER_WIDEN(value) WINNETMETER_WIDEN_INNER(value)
#define WINNETMETER_VERSION_STRING_W WINNETMETER_WIDEN(WINNETMETER_VERSION_STRING)
